// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfpVyafdo2Y02c1y2urO054W9AzcAcZVU',
    appId: '1:819589882304:web:3962a6aabc09f3c37a2825',
    messagingSenderId: '819589882304',
    projectId: 'flutter-firebase-23f30',
    authDomain: 'flutter-firebase-23f30.firebaseapp.com',
    storageBucket: 'flutter-firebase-23f30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA02aT3GekAtKBqQoS5Uj4X4F3mytCfuQ',
    appId: '1:819589882304:android:bc32a67a087b0fb47a2825',
    messagingSenderId: '819589882304',
    projectId: 'flutter-firebase-23f30',
    storageBucket: 'flutter-firebase-23f30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPCdK6A00UpKg1qfafsugq69JMAMOAkhg',
    appId: '1:819589882304:ios:66d948f8d3c7ccbc7a2825',
    messagingSenderId: '819589882304',
    projectId: 'flutter-firebase-23f30',
    storageBucket: 'flutter-firebase-23f30.firebasestorage.app',
    iosBundleId: 'com.example.tselUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPCdK6A00UpKg1qfafsugq69JMAMOAkhg',
    appId: '1:819589882304:ios:66d948f8d3c7ccbc7a2825',
    messagingSenderId: '819589882304',
    projectId: 'flutter-firebase-23f30',
    storageBucket: 'flutter-firebase-23f30.firebasestorage.app',
    iosBundleId: 'com.example.tselUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfpVyafdo2Y02c1y2urO054W9AzcAcZVU',
    appId: '1:819589882304:web:703e12c8336de3ff7a2825',
    messagingSenderId: '819589882304',
    projectId: 'flutter-firebase-23f30',
    authDomain: 'flutter-firebase-23f30.firebaseapp.com',
    storageBucket: 'flutter-firebase-23f30.firebasestorage.app',
  );
}
